
package Webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MyOntology", targetNamespace = "http://example/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MyOntology {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addIemToLastClicks", targetNamespace = "http://example/", className = "Webservice.AddIemToLastClicks")
    @ResponseWrapper(localName = "addIemToLastClicksResponse", targetNamespace = "http://example/", className = "Webservice.AddIemToLastClicksResponse")
    @Action(input = "http://example/MyOntology/addIemToLastClicksRequest", output = "http://example/MyOntology/addIemToLastClicksResponse")
    public void addIemToLastClicks(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListOfGenresIn", targetNamespace = "http://example/", className = "Webservice.GetListOfGenresIn")
    @ResponseWrapper(localName = "getListOfGenresInResponse", targetNamespace = "http://example/", className = "Webservice.GetListOfGenresInResponse")
    @Action(input = "http://example/MyOntology/getListOfGenresInRequest", output = "http://example/MyOntology/getListOfGenresInResponse")
    public List<String> getListOfGenresIn(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLastClicks", targetNamespace = "http://example/", className = "Webservice.GetLastClicks")
    @ResponseWrapper(localName = "getLastClicksResponse", targetNamespace = "http://example/", className = "Webservice.GetLastClicksResponse")
    @Action(input = "http://example/MyOntology/getLastClicksRequest", output = "http://example/MyOntology/getLastClicksResponse")
    public List<String> getLastClicks();

}
