
package Webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MyOntologyService", targetNamespace = "http://example/", wsdlLocation = "http://localhost:9000/Ontology?wsdl")
public class MyOntologyService
    extends Service
{

    private final static URL MYONTOLOGYSERVICE_WSDL_LOCATION;
    private final static WebServiceException MYONTOLOGYSERVICE_EXCEPTION;
    private final static QName MYONTOLOGYSERVICE_QNAME = new QName("http://example/", "MyOntologyService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9000/Ontology?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MYONTOLOGYSERVICE_WSDL_LOCATION = url;
        MYONTOLOGYSERVICE_EXCEPTION = e;
    }

    public MyOntologyService() {
        super(__getWsdlLocation(), MYONTOLOGYSERVICE_QNAME);
    }

    public MyOntologyService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MYONTOLOGYSERVICE_QNAME, features);
    }

    public MyOntologyService(URL wsdlLocation) {
        super(wsdlLocation, MYONTOLOGYSERVICE_QNAME);
    }

    public MyOntologyService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MYONTOLOGYSERVICE_QNAME, features);
    }

    public MyOntologyService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyOntologyService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MyOntology
     */
    @WebEndpoint(name = "MyOntologyPort")
    public MyOntology getMyOntologyPort() {
        return super.getPort(new QName("http://example/", "MyOntologyPort"), MyOntology.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MyOntology
     */
    @WebEndpoint(name = "MyOntologyPort")
    public MyOntology getMyOntologyPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://example/", "MyOntologyPort"), MyOntology.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MYONTOLOGYSERVICE_EXCEPTION!= null) {
            throw MYONTOLOGYSERVICE_EXCEPTION;
        }
        return MYONTOLOGYSERVICE_WSDL_LOCATION;
    }

}
